package Tela;

import Servidor.ActionManagement;
import Servidor.GameProtocolActionType;
import java.awt.event.KeyEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author gabriel
 */
public class GamePanel extends javax.swing.JFrame {

    Player player;
    Player player2;
    ActionManagement actionMng;
    PlacarUpdate placar;
    GameProtocolActionType lastAction;

    /**
     * Creates new form GamePanel
     */
    public GamePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHost = new javax.swing.JTextField();
        jPorta = new javax.swing.JTextField();
        bConectar = new javax.swing.JButton();
        lPlacar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });
        getContentPane().setLayout(null);

        jHost.setToolTipText("host");
        getContentPane().add(jHost);
        jHost.setBounds(70, 20, 110, 24);

        jPorta.setToolTipText("porta");
        jPorta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPortaActionPerformed(evt);
            }
        });
        getContentPane().add(jPorta);
        jPorta.setBounds(190, 20, 50, 24);

        bConectar.setText("Conectar");
        bConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConectarActionPerformed(evt);
            }
        });
        getContentPane().add(bConectar);
        bConectar.setBounds(250, 20, 90, 30);
        getContentPane().add(lPlacar);
        lPlacar.setBounds(250, 406, 280, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:

        GameProtocolActionType type = null;

        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {

            player.punch();
            int distanciaX = player.x - player2.x;
            int distanciaY = player.y - player2.y;
            if (distanciaX < 0) {
                distanciaX = distanciaX * -1;
            }
            if (distanciaY < 0) {
                distanciaY = distanciaY * -1;
            }

            if (distanciaX < 45 && distanciaY < 17) {
                if(lastAction != GameProtocolActionType.PUNCH){
                    player.points++;
                    player2.punched();
                        }
            }
            type = GameProtocolActionType.PUNCH;
        } else if (evt.getKeyCode() == KeyEvent.VK_LEFT) {

            player.moveLeft();
            type = GameProtocolActionType.MOVE_LEFT;
        } else if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {

            player.moveRight();
            type = GameProtocolActionType.MOVE_RIGHT;
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {

            player.moveUp();
            type = GameProtocolActionType.MOVE_UP;
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {

            player.moveDown();
            type = GameProtocolActionType.MOVE_DOWN;
        }
        
        lastAction = type;
        actionMng.sendAction(player.x, player.y, type);

    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased

       if(player2.wasPunched)
          player2.stand(); 
        
        player.stand();
        lastAction =  GameProtocolActionType.STAND;
        actionMng.sendAction(player.x, player.y, GameProtocolActionType.STAND);
    }//GEN-LAST:event_formKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowOpened

    private void bConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConectarActionPerformed

        getContentPane().remove(jHost);
        getContentPane().remove(jPorta);
        getContentPane().remove(bConectar);
        player = new Player();
        player.setup();
        player2 = new Player();
        player2.setup();
        player.grabFocus();
        actionMng = new ActionManagement(jHost.getText(), Integer.parseInt(jPorta.getText()), player, player2);
        actionMng.iniciar();
        getContentPane().add(player);
        getContentPane().add(player2);
        placar = new PlacarUpdate(player, player2, lPlacar);
        new Thread(placar).start();
        repaint();

    }//GEN-LAST:event_bConectarActionPerformed

    private void jPortaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPortaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPortaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GamePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GamePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GamePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GamePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GamePanel g = new GamePanel();
                g.setSize(800, 600);
                g.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bConectar;
    private javax.swing.JTextField jHost;
    private javax.swing.JTextField jPorta;
    private javax.swing.JLabel lPlacar;
    // End of variables declaration//GEN-END:variables
}
